# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
This module provides functionality to generate images and movies from fractals. It has three main building blocks. One for generating fractal images, one for animation and one for finding interesting focus points. For details see https://github.com/Carbonfreezer/fractal_python.
"""

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "AnimationPlayer",
    "AnimationRecorder",
    "ColorSystem",
    "FocalPointResult",
    "FocalSystemInterface",
    "FractalType",
    "IterationFieldInterface",
    "PathGenerationCriterion",
]

@typing.final
class AnimationPlayer:
    r"""
    Immutable animation produced by `AnimationRecorder.get_animation_player()`.
    Applies the animated values at a given time onto an `IterationFieldInterface`;
    reading a color field or an iteration field afterwards is up to the caller.
    """
    def max_time(self) -> builtins.float:
        r"""
        The end time of the animation: the latest key frame time across all
        tracks. Useful as the total duration when rendering or looping.
        """
    def apply_animation(self, time: builtins.float, interface: IterationFieldInterface) -> None:
        r"""
        Applies all animated values at `time` to the given field interface.
        After this call the interface reflects the animated state and the usual
        `get_color_field` / `get_*_iteration_field` methods can be used.
        """

@typing.final
class AnimationRecorder:
    r"""
    Builder for an animation. Key frames are added in this open state; calling
    [`get_animation_player`][AnimationRecorder.get_animation_player] freezes
    every track and returns an immutable `AnimationPlayer` that applies the
    animation to an `IterationFieldInterface`.
    
    The constructor seeds time 0. Its defaults mirror those of
    `IterationFieldInterface`, so an unconfigured animation starts on the same
    frame as an unconfigured field interface.
    
    Example:
    ```python
    from cinefractal import AnimationRecorder, IterationFieldInterface, FractalType, ColorSystem
    
    anim = AnimationRecorder(exponent=2, log_strength=5.0)
    anim.set_keyframe_fractal_seed_value(0.0, -0.7, 0.27)
    anim.set_keyframe_extension(6.0, 1e-4)
    animation = anim.get_animation_player()
    
    ifi = IterationFieldInterface()
    ifi.set_fractal_type(FractalType.julia())
    ifi.set_colorization_information(ColorSystem.inferno(), False)
    
    animation.apply_animation(3.0, ifi)
    color = ifi.get_color_field()
    ```
    """
    def __new__(cls, exponent: builtins.int = 2, julia_start_real: builtins.float = 0.0, julia_start_imag: builtins.float = 0.0, center_point_real: builtins.float = 0.0, center_point_imag: builtins.float = 0.0, extension: builtins.float = 1.5, max_iterations: builtins.int = 1000, log_strength: builtins.float = 0.0) -> AnimationRecorder:
        r"""
        Creates a new animation builder seeded at time 0.
        """
    def set_keyframe_exponent(self, time: builtins.float, exponent: builtins.int) -> None:
        r"""
        Adds a key frame for the iteration exponent. The exponent must be at
        least 2. The exponent is the exponent used in the escape time iteration formula.
        """
    def set_keyframe_fractal_seed_value(self, time: builtins.float, real: builtins.float, imag: builtins.float) -> None:
        r"""
        Adds a key frame for the fractal value. The Julia fractal is the only fractal, that
        has a start value as an additional parameter. One has to add real and imaginary parts.
        """
    def set_keyframe_render_center_point(self, time: builtins.float, real: builtins.float, imag: builtins.float) -> None:
        r"""
        Adds a key frame for the render center point. This is the point in the complex 
        number pane, that will be in the center of the image.
        """
    def set_keyframe_extension(self, time: builtins.float, extension: builtins.float) -> None:
        r"""
        Adds a key frame for the extension (zoom). Interpolated in logarithmic
        space, so the extension must be strictly positive.
        """
    def set_keyframe_max_iterations(self, time: builtins.float, max_iter: builtins.int) -> None:
        r"""
        Adds a key frame for the maximum number of iterations used in the escape iteration.
        Higher values mean more computation time but also more detailed fractal borders.
        """
    def set_keyframe_log_strength(self, time: builtins.float, log_strength: builtins.float) -> None:
        r"""
        Adds a key frame for the color log strength. The higher the log strength the more detailed
        the regions with low iteration values will be.
        """
    def get_animation_player(self) -> AnimationPlayer:
        r"""
        Freezes the current state into an immutable, queryable
        `AnimationPlayer`. The builder is cloned internally, so it stays
        usable afterwards: you can keep adding key frames and get another player,
        or reuse it as a template for several players.
        """

@typing.final
class ColorSystem:
    r"""
    Color scheme used to render the fractal. Supports different base colors.
    
    - Turbo
    - Viridis
    - Magma
    - Plasma
    - Inferno
    - Cool
    - cyclical : This is a rainbow like color scale with a repetition factor.
    
    Example:
    ```python
    cs = ColorSystem.viridis()
    cs = ColorSystem.cyclical(repetition_factor=3.0)
    ```
    """
    @staticmethod
    def turbo() -> ColorSystem: ...
    @staticmethod
    def viridis() -> ColorSystem: ...
    @staticmethod
    def magma() -> ColorSystem: ...
    @staticmethod
    def plasma() -> ColorSystem: ...
    @staticmethod
    def inferno() -> ColorSystem: ...
    @staticmethod
    def cool() -> ColorSystem: ...
    @staticmethod
    def cyclical(repetition_factor: builtins.float = 3.0) -> ColorSystem:
        r"""
        Cyclical color scheme with a configurable repetition factor.
        
        - `repetition_factor`: Repetition factor for cyclic color.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FocalPointResult:
    r"""
    Immutable result of an autofocus search, produced by
    `FocalSystemInterface.create_collection_of_points()`. Holds the best focal
    points and can hand them back either unordered (with their scores) or as an
    ordered path ready to drive an `AnimationRecorder`.
    """
    def get_focal_points_with_evaluation(self) -> builtins.list[tuple[builtins.float, builtins.float, builtins.float]]:
        r"""
        All focal points with their evaluation, unordered.
        Returns a list of `(real, imag, score)` tuples.
        """
    def get_path_from_start_point(self, criterion: PathGenerationCriterion, start_real: builtins.float = 0.0, start_imag: builtins.float = 0.0) -> builtins.list[tuple[builtins.float, builtins.float]]:
        r"""
        An ordered path through the focal points, starting at the given point.
        Returns a list of `(real, imag)` tuples; the start point is the first
        element.
        """
    def get_path_from_start_point_with_distance(self, criterion: PathGenerationCriterion, start_real: builtins.float = 0.0, start_imag: builtins.float = 0.0) -> builtins.list[tuple[builtins.float, builtins.float, builtins.float]]:
        r"""
        Like `get_path_from_start_point`, but each element is additionally
        annotated with the cumulative distance travelled along the path.
        Returns a list of `(real, imag, cumulative_distance)` tuples.
        Useful for timing an animation (e.g. constant-speed camera travel).
        """

@typing.final
class FocalSystemInterface:
    r"""
    Builder for an autofocus search. The fractal, search region and evaluation
    scale are configured through the micro setters; calling
    [`create_collection_of_points`][Self.create_collection_of_points] runs the
    (parallel) search and returns an immutable `FocalPointResult`.
    
    Mirrors `AnimationRecorder`: this object stays usable after producing a
    result, so you can tweak parameters and search again, or reuse it as a
    template for several searches.
    
    The constructor seeds the same defaults as an unconfigured
    `IterationFieldInterface`, so an autofocus run lines up with the field you
    intend to render.
    
    Example:
    ```python
    from cinefractal import FocalSystemInterface, FractalType
    
    focus = FocalSystemInterface(max_iterations=1000)
    focus.set_fractal_type(FractalType.mandelbrot())
    focus.set_center_point(-0.75, 0.0)
    focus.set_extension(1.5)        # search radius
    focus.set_evaluation_extension(1e-3)   # the render extension the points are judged at
    
    result = focus.create_collection_of_points(50)
    points = result.get_focal_points_with_evaluation()   # list of (re, im, score)
    ```
    """
    def __new__(cls, center_point_real: builtins.float = 0.0, center_point_imag: builtins.float = 0.0, extension: builtins.float = 1.5, extension_min: builtins.float = 0.0, evaluation_extension: builtins.float = 1.5, max_iterations: builtins.int = 1000) -> FocalSystemInterface:
        r"""
        Creates a new focal-system builder with default parameters:
        Mandelbrot (exponent 2), center 0, search extension 1.5,
        evaluation extension 1.5, no inner search radius, 1000 iterations.
        """
    def set_fractal_type(self, fractal_type: FractalType) -> None:
        r"""
        Sets the fractal type to search in (mandelbrot, julia, ...).
        """
    def set_fractal_exponent(self, exponent: builtins.int = 2) -> None:
        r"""
        Sets the iteration exponent. Must be at least 2. The exponent is the exponent used in 
        the escape time iteration formula.
        """
    def set_fractal_seed_value(self, real: builtins.float = 0.0, imag: builtins.float = 0.0) -> None:
        r"""
        Sets the Julia seed (start) value. Only relevant for the Julia set. The Julia fractal is the only fractal, that 
        has a start value as an additional parameter. One has to add real and imaginary parts.
        """
    def set_maximum_iterations(self, maximum_iterations: builtins.int = 1000) -> None:
        r"""
        Sets the maximum number of iterations used when sampling candidates.
        Higher values mean more computation time but also more detailed fractal borders.
        """
    def set_center_point(self, real: builtins.float = 0.0, imag: builtins.float = 0.0) -> None:
        r"""
        Sets the center of the circular search region in the complex number pane.
        """
    def set_extension(self, extension: builtins.float = 1.5) -> None:
        r"""
        Sets the outer search radius (and therefore the maximum distance of a
        candidate from the center). Must stay strictly greater than the current
        inner radius (`extension_min`).
        """
    def set_extension_min(self, extension_min: builtins.float = 0.0) -> None:
        r"""
        Sets the inner search radius. Candidates are scattered in the annulus
        between `extension_min` and `extension`. Defaults to 0 (full disc).
        Must satisfy `0 <= extension_min < extension`.
        """
    def set_evaluation_extension(self, evaluation_extension: builtins.float = 1.5) -> None:
        r"""
        Sets the evaluation extension: the rendering extension (the view's
        half-width in the complex plane) at which a candidate's local detail is
        measured. It should match the extension you later render the points at --
        note that a smaller value means a deeper zoom. Independent of the search
        extension (`set_extension`), which is usually larger.
        """
    def create_collection_of_points(self, num_of_points: builtins.int) -> FocalPointResult:
        r"""
        Runs the search and returns the best `num_of_points` candidates as an
        immutable `FocalPointResult`. The heavy, parallel work releases the GIL.
        """

@typing.final
class FractalType:
    r"""
    The kind of fractal to render. A pure tag -- the exponent and the Julia seed
    value are set separately on the `IterationFieldInterface` via
    `set_fractal_exponent` and `set_fractal_seed_value`. The latter is
    only relevant for the julia set visualization.
    
    Supported types:
    - mandelbrot
    - julia (uses the seed value)
    - burning_ship
    - tricorn
    - celtic
    
    Example:
    ```python
    from cinefractal import FractalType
    
    ft = FractalType.julia()
    ```
    """
    @staticmethod
    def mandelbrot() -> FractalType: ...
    @staticmethod
    def julia() -> FractalType: ...
    @staticmethod
    def burning_ship() -> FractalType: ...
    @staticmethod
    def tricorn() -> FractalType: ...
    @staticmethod
    def celtic() -> FractalType: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class IterationFieldInterface:
    r"""
    Main interface for computing fractals. This is the entry point for generating images and
    iteration fields. A base is setup with default parameters, that can be adjusted by individual methods.
    
    Example:
    ```python
    from cinefractal import IterationFieldInterface, FractalType, ColorSystem
    
    ifi = IterationFieldInterface()
    ifi.set_numpy_extension(768, 1024)
    ifi.set_fractal_type(FractalType.mandelbrot())
    ifi.set_fractal_exponent(2)
    ifi.set_colorization_information(ColorSystem.viridis(), True)
    color = ifi.get_color_field()   # numpy array (rows, cols, 3), dtype=uint8
    ```
    """
    def __new__(cls) -> IterationFieldInterface:
        r"""
        Creates a new instance with default values:
        1024×768, Mandelbrot (exponent 2), Viridis, discrete coloring, no log scaling.
        """
    def set_numpy_extension(self, rows: builtins.int, columns: builtins.int) -> None:
        r"""
        Sets the output size in pixels
        
        - rows = height
        - columns = width
        """
    def set_fractal_type(self, fractal_type: FractalType) -> None:
        r"""
        Sets the fractal type to render.
        
        - fractal_type: a `FractalType` (mandelbrot, julia, ...)
        """
    def set_fractal_exponent(self, exponent: builtins.int = 2) -> None:
        r"""
        Sets the iteration exponent. Must be at least 2. The exponent is the exponent 
        used in the escape time iteration formula.
        """
    def set_fractal_seed_value(self, real: builtins.float = 0.0, imag: builtins.float = 0.0) -> None:
        r"""
        Sets the Julia seed (start) value. The Julia fractal is the only fractal, that 
        has a start value as an additional parameter. One has to add real and imaginary parts.
        """
    def set_maximum_iterations(self, maximum_iterations: builtins.int = 1000) -> None:
        r"""
        Sets the maximum number of iterations used in the escape iteration.
        Higher values mean more computation time but also more detailed fractal borders.
        """
    def set_center_point(self, real: builtins.float = 0.0, imag: builtins.float = 0.0) -> None:
        r"""
        Sets the center point in the complex plane. This is the point in the complex 
        number pane, that will be in the center of the image.
        """
    def set_extension(self, extension: builtins.float = 1.5) -> None:
        r"""
        Sets the extension (inverse zoom factor) in the complex plane.
        """
    def set_colorization_information(self, color_system: ColorSystem, uses_discrete_for_color: builtins.bool = False) -> None:
        r"""
        Sets the color scheme and discrete/continuous mode.
        
        - `color_system`: the desired color scheme
        - `uses_discrete_for_color`: True = discrete iteration counts, False = continuous
        
        The logarithmic color strength is set separately with
        `set_colorization_log_strength`.
        """
    def set_colorization_log_strength(self, log_strength: builtins.float = 0.0) -> None:
        r"""
        Sets the strength of the logarithmic color scaling (0.0 = off).
        
        Note: when an animation is applied to this interface, this value is
        driven by the animation's log strength track and overwritten each frame.
        """
    def get_discrete_iteration_field(self) -> numpy.typing.NDArray[numpy.uint16]:
        r"""
        Returns the discrete iteration field (shape: rows × cols, dtype: uint16).
        """
    def get_continuous_iteration_field(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Returns the continuous iteration field (shape: rows × cols, dtype: float32).
        """
    def get_color_field(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Returns the RGB color image (shape: rows × cols × 3, dtype: uint8).
        """

@typing.final
class PathGenerationCriterion:
    r"""
    How focal points are ordered when a path through them is requested.
    
    A pure tag, mirroring `FractalType`. Pick the construction strategy via the
    static methods.
    
    - `short_path`: a reasonably short tour (greedy TSP approximation), starting
      at the point closest to the supplied start point. Good for smooth camera
      travel.
    - `descending_value`: most-interesting point first, down to the least
      interesting. Good for a "highlight reel" ordering. The start point is
      ignored for ordering but still prepended to the resulting path.
    
    Example:
    ```python
    from cinefractal import PathGenerationCriterion
    
    crit = PathGenerationCriterion.short_path()
    ```
    """
    @staticmethod
    def short_path() -> PathGenerationCriterion:
        r"""
        Greedy short tour starting from the point nearest the start point.
        """
    @staticmethod
    def descending_value() -> PathGenerationCriterion:
        r"""
        Points ordered from most to least interesting.
        """
    def __repr__(self) -> builtins.str: ...

